### ISSUE TITLE
Search can only be performed with one word

### ISSUE THREAD

**Issue by andrewblaney** [bbc/summa-transcriber#2]

**Comment by mhumph** [comment]
It's clicking through from the results screen to the details screen that doesn't work with multiple words.

See TranscriptionViewer.vue

**Comment by mhumph** [comment]
Committed a first pass of this to master. It's hacky. The real solution is to get the char index of the start and end of each highlight. We could then match that against our text.

Elasticsearch doesn't seem to directly support this but we could do it ourselves by matching each highlight/context against the actual text to get char positions. Not worth it for now.

**Comment by mhumph** [comment]
PS. i had to hack some of the php to get this working on my machine... i didn't commit the php hacks... probs just something to do with my setup.
