### ISSUE TITLE
Handle failed transcriptions

### ISSUE THREAD

**Issue by andrewblaney** [bbc/summa-transcriber#4]
- Do we need to retry? Will this solve the issue or is there something wrong with the file to make it fail.
- Should we throw them away (can cause holes in the live feed)
- Option to clear failed transcriptions from FE log page

**Comment by mhumph** [comment]
This should work (in docker-compose.yml > elasticsearch > environment):

- cluster.routing.allocation.disk.threshold_enabled=true
- cluster.routing.allocation.disk.watermark.low=30gb
- cluster.routing.allocation.disk.watermark.high=20gb
- cluster.routing.allocation.disk.watermark.flood_stage=10gb

**Comment by mhumph** [comment]
The config below works on my laptop. My container only has 17 Gb free.

- cluster.routing.allocation.disk.threshold_enabled=true
- cluster.routing.allocation.disk.watermark.low=4gb
- cluster.routing.allocation.disk.watermark.high=2gb
- cluster.routing.allocation.disk.watermark.flood_stage=1gb

**Comment by mhumph** [comment]
Fails consistently on my laptop, and on the server with master checked out.

Improvement pushed to master but the js code around messages still need some work. 

Let's not worry about clearing failed transcriptions yet.
