### ISSUE TITLE
Fix elasticsearch memory warnings

### ISSUE THREAD

**Issue by andrewblaney** [bbc/summa-transcriber#9]
The watermark thresholds need setting so that annoying error messages in docker logs are silenced 

https://stackoverflow.com/questions/33369955/low-disk-watermark-exceeded-on

**Comment by mhumph** [comment]
The config below works on my laptop. My container only has 17 Gb free.

cluster.routing.allocation.disk.threshold_enabled=true
cluster.routing.allocation.disk.watermark.low=4gb
cluster.routing.allocation.disk.watermark.high=2gb
cluster.routing.allocation.disk.watermark.flood_stage=1gb

**Comment by mhumph** [comment]
Fixed on master
